// Code generated by protoc-gen-go. DO NOT EDIT.
// source: cs3/auth/v0alpha/auth.proto

package authv0alphapb

import (
	context "context"
	fmt "fmt"
	rpc "github.com/cs3org/go-cs3apis/cs3/rpc"
	types "github.com/cs3org/go-cs3apis/cs3/types"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GenerateAccessTokenRequest struct {
	ClientId             string   `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	ClientSecret         string   `protobuf:"bytes,2,opt,name=client_secret,json=clientSecret,proto3" json:"client_secret,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GenerateAccessTokenRequest) Reset()         { *m = GenerateAccessTokenRequest{} }
func (m *GenerateAccessTokenRequest) String() string { return proto.CompactTextString(m) }
func (*GenerateAccessTokenRequest) ProtoMessage()    {}
func (*GenerateAccessTokenRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1ae21de9dc3d6621, []int{0}
}

func (m *GenerateAccessTokenRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GenerateAccessTokenRequest.Unmarshal(m, b)
}
func (m *GenerateAccessTokenRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GenerateAccessTokenRequest.Marshal(b, m, deterministic)
}
func (m *GenerateAccessTokenRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenerateAccessTokenRequest.Merge(m, src)
}
func (m *GenerateAccessTokenRequest) XXX_Size() int {
	return xxx_messageInfo_GenerateAccessTokenRequest.Size(m)
}
func (m *GenerateAccessTokenRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GenerateAccessTokenRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GenerateAccessTokenRequest proto.InternalMessageInfo

func (m *GenerateAccessTokenRequest) GetClientId() string {
	if m != nil {
		return m.ClientId
	}
	return ""
}

func (m *GenerateAccessTokenRequest) GetClientSecret() string {
	if m != nil {
		return m.ClientSecret
	}
	return ""
}

type GenerateAccessTokenResponse struct {
	Status               *rpc.Status   `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	AccessToken          string        `protobuf:"bytes,2,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	UserId               *types.UserId `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *GenerateAccessTokenResponse) Reset()         { *m = GenerateAccessTokenResponse{} }
func (m *GenerateAccessTokenResponse) String() string { return proto.CompactTextString(m) }
func (*GenerateAccessTokenResponse) ProtoMessage()    {}
func (*GenerateAccessTokenResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1ae21de9dc3d6621, []int{1}
}

func (m *GenerateAccessTokenResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GenerateAccessTokenResponse.Unmarshal(m, b)
}
func (m *GenerateAccessTokenResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GenerateAccessTokenResponse.Marshal(b, m, deterministic)
}
func (m *GenerateAccessTokenResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenerateAccessTokenResponse.Merge(m, src)
}
func (m *GenerateAccessTokenResponse) XXX_Size() int {
	return xxx_messageInfo_GenerateAccessTokenResponse.Size(m)
}
func (m *GenerateAccessTokenResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GenerateAccessTokenResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GenerateAccessTokenResponse proto.InternalMessageInfo

func (m *GenerateAccessTokenResponse) GetStatus() *rpc.Status {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *GenerateAccessTokenResponse) GetAccessToken() string {
	if m != nil {
		return m.AccessToken
	}
	return ""
}

func (m *GenerateAccessTokenResponse) GetUserId() *types.UserId {
	if m != nil {
		return m.UserId
	}
	return nil
}

type WhoAmIRequest struct {
	AccessToken          string   `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WhoAmIRequest) Reset()         { *m = WhoAmIRequest{} }
func (m *WhoAmIRequest) String() string { return proto.CompactTextString(m) }
func (*WhoAmIRequest) ProtoMessage()    {}
func (*WhoAmIRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1ae21de9dc3d6621, []int{2}
}

func (m *WhoAmIRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WhoAmIRequest.Unmarshal(m, b)
}
func (m *WhoAmIRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WhoAmIRequest.Marshal(b, m, deterministic)
}
func (m *WhoAmIRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WhoAmIRequest.Merge(m, src)
}
func (m *WhoAmIRequest) XXX_Size() int {
	return xxx_messageInfo_WhoAmIRequest.Size(m)
}
func (m *WhoAmIRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_WhoAmIRequest.DiscardUnknown(m)
}

var xxx_messageInfo_WhoAmIRequest proto.InternalMessageInfo

func (m *WhoAmIRequest) GetAccessToken() string {
	if m != nil {
		return m.AccessToken
	}
	return ""
}

type WhoAmIResponse struct {
	Status               *rpc.Status `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	User                 *User       `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *WhoAmIResponse) Reset()         { *m = WhoAmIResponse{} }
func (m *WhoAmIResponse) String() string { return proto.CompactTextString(m) }
func (*WhoAmIResponse) ProtoMessage()    {}
func (*WhoAmIResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1ae21de9dc3d6621, []int{3}
}

func (m *WhoAmIResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WhoAmIResponse.Unmarshal(m, b)
}
func (m *WhoAmIResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WhoAmIResponse.Marshal(b, m, deterministic)
}
func (m *WhoAmIResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WhoAmIResponse.Merge(m, src)
}
func (m *WhoAmIResponse) XXX_Size() int {
	return xxx_messageInfo_WhoAmIResponse.Size(m)
}
func (m *WhoAmIResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_WhoAmIResponse.DiscardUnknown(m)
}

var xxx_messageInfo_WhoAmIResponse proto.InternalMessageInfo

func (m *WhoAmIResponse) GetStatus() *rpc.Status {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *WhoAmIResponse) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

func init() {
	proto.RegisterType((*GenerateAccessTokenRequest)(nil), "cs3.authv0alpha.GenerateAccessTokenRequest")
	proto.RegisterType((*GenerateAccessTokenResponse)(nil), "cs3.authv0alpha.GenerateAccessTokenResponse")
	proto.RegisterType((*WhoAmIRequest)(nil), "cs3.authv0alpha.WhoAmIRequest")
	proto.RegisterType((*WhoAmIResponse)(nil), "cs3.authv0alpha.WhoAmIResponse")
}

func init() { proto.RegisterFile("cs3/auth/v0alpha/auth.proto", fileDescriptor_1ae21de9dc3d6621) }

var fileDescriptor_1ae21de9dc3d6621 = []byte{
	// 404 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x52, 0xdd, 0x8a, 0xda, 0x40,
	0x18, 0x25, 0xb6, 0xa4, 0x75, 0xa2, 0x95, 0x8e, 0x15, 0x24, 0x42, 0x6b, 0xd3, 0x8b, 0xfe, 0x12,
	0x25, 0x79, 0x82, 0xc4, 0x8b, 0x92, 0xab, 0x4a, 0xd2, 0x3f, 0x4a, 0x51, 0xe2, 0xe4, 0x83, 0x48,
	0x35, 0x99, 0xce, 0x4c, 0x84, 0x3e, 0x48, 0x5f, 0x60, 0x2f, 0xf7, 0x51, 0x7c, 0xaa, 0x65, 0x66,
	0x22, 0xeb, 0x1a, 0x85, 0xdd, 0x9b, 0x84, 0x39, 0xe7, 0x7c, 0x67, 0xce, 0x99, 0x19, 0x34, 0x22,
	0xdc, 0x9f, 0xa4, 0x95, 0xc8, 0x27, 0xbb, 0x69, 0xba, 0xa1, 0x79, 0xaa, 0x16, 0x2e, 0x65, 0xa5,
	0x28, 0x71, 0x8f, 0x70, 0xdf, 0x95, 0xeb, 0x9a, 0xb3, 0xc7, 0x0d, 0x35, 0x03, 0x5e, 0x56, 0x8c,
	0x00, 0xd7, 0x23, 0xf6, 0x0b, 0xa9, 0x60, 0x94, 0x4c, 0xb8, 0x48, 0x45, 0x75, 0x40, 0x07, 0x12,
	0x15, 0xff, 0x28, 0x70, 0xfd, 0xd5, 0xb0, 0xb3, 0x40, 0xf6, 0x67, 0x28, 0x80, 0xa5, 0x02, 0x02,
	0x42, 0x80, 0xf3, 0xaf, 0xe5, 0x1f, 0x28, 0x62, 0xf8, 0x5b, 0x01, 0x17, 0x78, 0x84, 0xda, 0x64,
	0xb3, 0x86, 0x42, 0x2c, 0xd7, 0xd9, 0xd0, 0x18, 0x1b, 0xef, 0xda, 0xf1, 0x53, 0x0d, 0x44, 0x19,
	0x7e, 0x83, 0xba, 0x35, 0xc9, 0x81, 0x30, 0x10, 0xc3, 0x96, 0x12, 0x74, 0x34, 0x98, 0x28, 0xcc,
	0xf9, 0x6f, 0xa0, 0xd1, 0xd9, 0x0d, 0x38, 0x2d, 0x0b, 0x0e, 0xf8, 0x2d, 0x32, 0x75, 0x4c, 0x65,
	0x6f, 0x79, 0x3d, 0x57, 0x16, 0x66, 0x94, 0xb8, 0x89, 0x82, 0xe3, 0x9a, 0xc6, 0xaf, 0x51, 0x27,
	0x55, 0xf3, 0x4b, 0x21, 0x0d, 0xea, 0xcd, 0xac, 0xf4, 0xd6, 0x13, 0x7f, 0x40, 0x4f, 0x2a, 0x0e,
	0x4c, 0x66, 0x7d, 0xa4, 0xcc, 0x9e, 0x2b, 0x33, 0x5d, 0xf7, 0x1b, 0x07, 0x16, 0x65, 0xb1, 0x59,
	0xa9, 0xbf, 0xe3, 0xa1, 0xee, 0x8f, 0xbc, 0x0c, 0xb6, 0xd1, 0xa1, 0xea, 0xa9, 0xbf, 0xd1, 0xf0,
	0x77, 0x32, 0xf4, 0xec, 0x30, 0xf3, 0xd0, 0xf4, 0xef, 0xd1, 0x63, 0xb9, 0xb1, 0x4a, 0x6d, 0x79,
	0x03, 0xf7, 0xe4, 0x56, 0x55, 0xba, 0x58, 0x49, 0xbc, 0xbd, 0x81, 0xac, 0xa0, 0x12, 0x79, 0x02,
	0x6c, 0xb7, 0x26, 0x80, 0x29, 0xea, 0x9f, 0x39, 0x40, 0xfc, 0xb1, 0xe1, 0x71, 0xf9, 0x1e, 0xed,
	0x4f, 0xf7, 0x13, 0xd7, 0xad, 0x22, 0x64, 0xea, 0x9e, 0xf8, 0x65, 0x63, 0xee, 0xce, 0xa1, 0xd9,
	0xaf, 0x2e, 0xf2, 0xda, 0x2a, 0x5c, 0xa0, 0x3e, 0x29, 0xb7, 0xa7, 0xaa, 0xb0, 0x2d, 0x0b, 0xce,
	0xe5, 0x03, 0x9c, 0x1b, 0xbf, 0xba, 0x47, 0x0c, 0x5d, 0x5d, 0xb5, 0xcc, 0x59, 0xf8, 0xe5, 0x67,
	0x10, 0x5e, 0xb7, 0x7a, 0xb3, 0xc4, 0x77, 0xa5, 0xf2, 0xfb, 0x34, 0x90, 0xe4, 0x5e, 0x21, 0xbf,
	0x8f, 0x90, 0x95, 0xa9, 0x5e, 0xb1, 0x7f, 0x13, 0x00, 0x00, 0xff, 0xff, 0xe4, 0x50, 0xb9, 0x4b,
	0x44, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// AuthServiceClient is the client API for AuthService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AuthServiceClient interface {
	GenerateAccessToken(ctx context.Context, in *GenerateAccessTokenRequest, opts ...grpc.CallOption) (*GenerateAccessTokenResponse, error)
	WhoAmI(ctx context.Context, in *WhoAmIRequest, opts ...grpc.CallOption) (*WhoAmIResponse, error)
}

type authServiceClient struct {
	cc *grpc.ClientConn
}

func NewAuthServiceClient(cc *grpc.ClientConn) AuthServiceClient {
	return &authServiceClient{cc}
}

func (c *authServiceClient) GenerateAccessToken(ctx context.Context, in *GenerateAccessTokenRequest, opts ...grpc.CallOption) (*GenerateAccessTokenResponse, error) {
	out := new(GenerateAccessTokenResponse)
	err := c.cc.Invoke(ctx, "/cs3.authv0alpha.AuthService/GenerateAccessToken", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) WhoAmI(ctx context.Context, in *WhoAmIRequest, opts ...grpc.CallOption) (*WhoAmIResponse, error) {
	out := new(WhoAmIResponse)
	err := c.cc.Invoke(ctx, "/cs3.authv0alpha.AuthService/WhoAmI", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AuthServiceServer is the server API for AuthService service.
type AuthServiceServer interface {
	GenerateAccessToken(context.Context, *GenerateAccessTokenRequest) (*GenerateAccessTokenResponse, error)
	WhoAmI(context.Context, *WhoAmIRequest) (*WhoAmIResponse, error)
}

// UnimplementedAuthServiceServer can be embedded to have forward compatible implementations.
type UnimplementedAuthServiceServer struct {
}

func (*UnimplementedAuthServiceServer) GenerateAccessToken(ctx context.Context, req *GenerateAccessTokenRequest) (*GenerateAccessTokenResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GenerateAccessToken not implemented")
}
func (*UnimplementedAuthServiceServer) WhoAmI(ctx context.Context, req *WhoAmIRequest) (*WhoAmIResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method WhoAmI not implemented")
}

func RegisterAuthServiceServer(s *grpc.Server, srv AuthServiceServer) {
	s.RegisterService(&_AuthService_serviceDesc, srv)
}

func _AuthService_GenerateAccessToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GenerateAccessTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).GenerateAccessToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cs3.authv0alpha.AuthService/GenerateAccessToken",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).GenerateAccessToken(ctx, req.(*GenerateAccessTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_WhoAmI_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WhoAmIRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).WhoAmI(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cs3.authv0alpha.AuthService/WhoAmI",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).WhoAmI(ctx, req.(*WhoAmIRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _AuthService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "cs3.authv0alpha.AuthService",
	HandlerType: (*AuthServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GenerateAccessToken",
			Handler:    _AuthService_GenerateAccessToken_Handler,
		},
		{
			MethodName: "WhoAmI",
			Handler:    _AuthService_WhoAmI_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "cs3/auth/v0alpha/auth.proto",
}
