// Code generated by protoc-gen-go. DO NOT EDIT.
// source: cs3/storage/registry/v1beta1/registry_api.proto

package registryv1beta1

import (
	context "context"
	fmt "fmt"
	v1beta12 "github.com/cs3org/go-cs3apis/cs3/rpc/v1beta1"
	v1beta11 "github.com/cs3org/go-cs3apis/cs3/storage/provider/v1beta1"
	v1beta1 "github.com/cs3org/go-cs3apis/cs3/types/v1beta1"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GetStorageProviderRequest struct {
	// OPTIONAL.
	// Opaque information.
	Opaque *v1beta1.Opaque `protobuf:"bytes,1,opt,name=opaque,proto3" json:"opaque,omitempty"`
	// REQUIRED.
	// The reference for the resource.
	Ref                  *v1beta11.Reference `protobuf:"bytes,2,opt,name=ref,proto3" json:"ref,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *GetStorageProviderRequest) Reset()         { *m = GetStorageProviderRequest{} }
func (m *GetStorageProviderRequest) String() string { return proto.CompactTextString(m) }
func (*GetStorageProviderRequest) ProtoMessage()    {}
func (*GetStorageProviderRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_73c91f9d6bdb642a, []int{0}
}

func (m *GetStorageProviderRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetStorageProviderRequest.Unmarshal(m, b)
}
func (m *GetStorageProviderRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetStorageProviderRequest.Marshal(b, m, deterministic)
}
func (m *GetStorageProviderRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetStorageProviderRequest.Merge(m, src)
}
func (m *GetStorageProviderRequest) XXX_Size() int {
	return xxx_messageInfo_GetStorageProviderRequest.Size(m)
}
func (m *GetStorageProviderRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetStorageProviderRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetStorageProviderRequest proto.InternalMessageInfo

func (m *GetStorageProviderRequest) GetOpaque() *v1beta1.Opaque {
	if m != nil {
		return m.Opaque
	}
	return nil
}

func (m *GetStorageProviderRequest) GetRef() *v1beta11.Reference {
	if m != nil {
		return m.Ref
	}
	return nil
}

type GetStorageProviderResponse struct {
	// REQUIRED.
	// The response status.
	Status *v1beta12.Status `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	// OPTIONAL.
	// Opaque information.
	Opaque *v1beta1.Opaque `protobuf:"bytes,2,opt,name=opaque,proto3" json:"opaque,omitempty"`
	// REQUIRED.
	// The storage provider handling the requested storage resource.
	Provider             *ProviderInfo `protobuf:"bytes,3,opt,name=provider,proto3" json:"provider,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *GetStorageProviderResponse) Reset()         { *m = GetStorageProviderResponse{} }
func (m *GetStorageProviderResponse) String() string { return proto.CompactTextString(m) }
func (*GetStorageProviderResponse) ProtoMessage()    {}
func (*GetStorageProviderResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_73c91f9d6bdb642a, []int{1}
}

func (m *GetStorageProviderResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetStorageProviderResponse.Unmarshal(m, b)
}
func (m *GetStorageProviderResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetStorageProviderResponse.Marshal(b, m, deterministic)
}
func (m *GetStorageProviderResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetStorageProviderResponse.Merge(m, src)
}
func (m *GetStorageProviderResponse) XXX_Size() int {
	return xxx_messageInfo_GetStorageProviderResponse.Size(m)
}
func (m *GetStorageProviderResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetStorageProviderResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetStorageProviderResponse proto.InternalMessageInfo

func (m *GetStorageProviderResponse) GetStatus() *v1beta12.Status {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *GetStorageProviderResponse) GetOpaque() *v1beta1.Opaque {
	if m != nil {
		return m.Opaque
	}
	return nil
}

func (m *GetStorageProviderResponse) GetProvider() *ProviderInfo {
	if m != nil {
		return m.Provider
	}
	return nil
}

type ListStorageProvidersRequest struct {
	// OPTIONAL.
	// Opaque information.
	Opaque               *v1beta1.Opaque `protobuf:"bytes,1,opt,name=opaque,proto3" json:"opaque,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *ListStorageProvidersRequest) Reset()         { *m = ListStorageProvidersRequest{} }
func (m *ListStorageProvidersRequest) String() string { return proto.CompactTextString(m) }
func (*ListStorageProvidersRequest) ProtoMessage()    {}
func (*ListStorageProvidersRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_73c91f9d6bdb642a, []int{2}
}

func (m *ListStorageProvidersRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListStorageProvidersRequest.Unmarshal(m, b)
}
func (m *ListStorageProvidersRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListStorageProvidersRequest.Marshal(b, m, deterministic)
}
func (m *ListStorageProvidersRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListStorageProvidersRequest.Merge(m, src)
}
func (m *ListStorageProvidersRequest) XXX_Size() int {
	return xxx_messageInfo_ListStorageProvidersRequest.Size(m)
}
func (m *ListStorageProvidersRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListStorageProvidersRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListStorageProvidersRequest proto.InternalMessageInfo

func (m *ListStorageProvidersRequest) GetOpaque() *v1beta1.Opaque {
	if m != nil {
		return m.Opaque
	}
	return nil
}

type ListStorageProvidersResponse struct {
	// REQUIRED.
	// The response status.
	Status *v1beta12.Status `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	// OPTIONAL.
	// Opaque information.
	Opaque *v1beta1.Opaque `protobuf:"bytes,2,opt,name=opaque,proto3" json:"opaque,omitempty"`
	// REQUIRED.
	// The list of storage providers this registry knows about.
	Providers            []*ProviderInfo `protobuf:"bytes,3,rep,name=providers,proto3" json:"providers,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *ListStorageProvidersResponse) Reset()         { *m = ListStorageProvidersResponse{} }
func (m *ListStorageProvidersResponse) String() string { return proto.CompactTextString(m) }
func (*ListStorageProvidersResponse) ProtoMessage()    {}
func (*ListStorageProvidersResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_73c91f9d6bdb642a, []int{3}
}

func (m *ListStorageProvidersResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListStorageProvidersResponse.Unmarshal(m, b)
}
func (m *ListStorageProvidersResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListStorageProvidersResponse.Marshal(b, m, deterministic)
}
func (m *ListStorageProvidersResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListStorageProvidersResponse.Merge(m, src)
}
func (m *ListStorageProvidersResponse) XXX_Size() int {
	return xxx_messageInfo_ListStorageProvidersResponse.Size(m)
}
func (m *ListStorageProvidersResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListStorageProvidersResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListStorageProvidersResponse proto.InternalMessageInfo

func (m *ListStorageProvidersResponse) GetStatus() *v1beta12.Status {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *ListStorageProvidersResponse) GetOpaque() *v1beta1.Opaque {
	if m != nil {
		return m.Opaque
	}
	return nil
}

func (m *ListStorageProvidersResponse) GetProviders() []*ProviderInfo {
	if m != nil {
		return m.Providers
	}
	return nil
}

type GetHomeRequest struct {
	// OPTIONAL.
	// Opaque information.
	Opaque               *v1beta1.Opaque `protobuf:"bytes,1,opt,name=opaque,proto3" json:"opaque,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *GetHomeRequest) Reset()         { *m = GetHomeRequest{} }
func (m *GetHomeRequest) String() string { return proto.CompactTextString(m) }
func (*GetHomeRequest) ProtoMessage()    {}
func (*GetHomeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_73c91f9d6bdb642a, []int{4}
}

func (m *GetHomeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetHomeRequest.Unmarshal(m, b)
}
func (m *GetHomeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetHomeRequest.Marshal(b, m, deterministic)
}
func (m *GetHomeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetHomeRequest.Merge(m, src)
}
func (m *GetHomeRequest) XXX_Size() int {
	return xxx_messageInfo_GetHomeRequest.Size(m)
}
func (m *GetHomeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetHomeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetHomeRequest proto.InternalMessageInfo

func (m *GetHomeRequest) GetOpaque() *v1beta1.Opaque {
	if m != nil {
		return m.Opaque
	}
	return nil
}

type GetHomeResponse struct {
	// REQUIRED.
	// The response status.
	Status *v1beta12.Status `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	// OPTIONAL.
	// Opaque information.
	Opaque *v1beta1.Opaque `protobuf:"bytes,2,opt,name=opaque,proto3" json:"opaque,omitempty"`
	// REQUIRED.
	// The path to the home in a storage provider.
	// For example /eos/user/h/hugo in the storage provider with root path /eos/user/.
	Path string `protobuf:"bytes,3,opt,name=path,proto3" json:"path,omitempty"`
	// REQUIRED.
	// The home storage provider.
	Provider             *ProviderInfo `protobuf:"bytes,4,opt,name=provider,proto3" json:"provider,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *GetHomeResponse) Reset()         { *m = GetHomeResponse{} }
func (m *GetHomeResponse) String() string { return proto.CompactTextString(m) }
func (*GetHomeResponse) ProtoMessage()    {}
func (*GetHomeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_73c91f9d6bdb642a, []int{5}
}

func (m *GetHomeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetHomeResponse.Unmarshal(m, b)
}
func (m *GetHomeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetHomeResponse.Marshal(b, m, deterministic)
}
func (m *GetHomeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetHomeResponse.Merge(m, src)
}
func (m *GetHomeResponse) XXX_Size() int {
	return xxx_messageInfo_GetHomeResponse.Size(m)
}
func (m *GetHomeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetHomeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetHomeResponse proto.InternalMessageInfo

func (m *GetHomeResponse) GetStatus() *v1beta12.Status {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *GetHomeResponse) GetOpaque() *v1beta1.Opaque {
	if m != nil {
		return m.Opaque
	}
	return nil
}

func (m *GetHomeResponse) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func (m *GetHomeResponse) GetProvider() *ProviderInfo {
	if m != nil {
		return m.Provider
	}
	return nil
}

func init() {
	proto.RegisterType((*GetStorageProviderRequest)(nil), "cs3.storage.registry.v1beta1.GetStorageProviderRequest")
	proto.RegisterType((*GetStorageProviderResponse)(nil), "cs3.storage.registry.v1beta1.GetStorageProviderResponse")
	proto.RegisterType((*ListStorageProvidersRequest)(nil), "cs3.storage.registry.v1beta1.ListStorageProvidersRequest")
	proto.RegisterType((*ListStorageProvidersResponse)(nil), "cs3.storage.registry.v1beta1.ListStorageProvidersResponse")
	proto.RegisterType((*GetHomeRequest)(nil), "cs3.storage.registry.v1beta1.GetHomeRequest")
	proto.RegisterType((*GetHomeResponse)(nil), "cs3.storage.registry.v1beta1.GetHomeResponse")
}

func init() {
	proto.RegisterFile("cs3/storage/registry/v1beta1/registry_api.proto", fileDescriptor_73c91f9d6bdb642a)
}

var fileDescriptor_73c91f9d6bdb642a = []byte{
	// 496 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x54, 0xd1, 0x6a, 0x13, 0x41,
	0x14, 0x65, 0xb2, 0x25, 0xda, 0x5b, 0xb0, 0x32, 0x08, 0xa6, 0x6b, 0x84, 0xb0, 0x2f, 0x8a, 0xd4,
	0x59, 0xd2, 0x3c, 0x68, 0x7d, 0x33, 0x01, 0xdb, 0x82, 0xe0, 0x32, 0x01, 0x1f, 0x24, 0x20, 0xdb,
	0xf5, 0xa6, 0xee, 0x43, 0x33, 0xd3, 0x99, 0x49, 0xa1, 0x5f, 0x20, 0x22, 0xe2, 0x3f, 0xf8, 0xe8,
	0x97, 0x88, 0xf8, 0xe2, 0x1f, 0xc9, 0xce, 0xce, 0x8e, 0x5b, 0x5d, 0xd7, 0x36, 0x42, 0xdf, 0x92,
	0xbd, 0xe7, 0x9c, 0x7b, 0xee, 0x99, 0x3b, 0x03, 0x71, 0xa6, 0x47, 0xb1, 0x36, 0x42, 0xa5, 0x47,
	0x18, 0x2b, 0x3c, 0xca, 0xb5, 0x51, 0x67, 0xf1, 0xe9, 0xf0, 0x10, 0x4d, 0x3a, 0xf4, 0x1f, 0x5e,
	0xa7, 0x32, 0x67, 0x52, 0x09, 0x23, 0x68, 0x3f, 0xd3, 0x23, 0xe6, 0x08, 0xac, 0xaa, 0x33, 0x47,
	0x08, 0x8b, 0x6a, 0xac, 0x64, 0xe6, 0x15, 0xb4, 0x49, 0xcd, 0x52, 0x97, 0xdc, 0x70, 0xbb, 0xde,
	0x4c, 0x2a, 0x71, 0x9a, 0xbf, 0x41, 0x55, 0x6b, 0xa6, 0xc5, 0x52, 0x65, 0xd8, 0x88, 0x6e, 0xb0,
	0x76, 0x1e, 0x7d, 0xb7, 0x40, 0x9b, 0x33, 0x89, 0xda, 0x43, 0xec, 0xbf, 0xb2, 0x1c, 0xbd, 0x27,
	0xb0, 0xb5, 0x87, 0x66, 0x5a, 0xca, 0x25, 0xae, 0x37, 0xc7, 0x93, 0x25, 0x6a, 0x43, 0x87, 0xd0,
	0x15, 0x32, 0x3d, 0x59, 0x62, 0x8f, 0x0c, 0xc8, 0xfd, 0x8d, 0x9d, 0x2d, 0x56, 0x4c, 0x59, 0xf2,
	0x9d, 0x1a, 0x7b, 0x61, 0x01, 0xdc, 0x01, 0xe9, 0x2e, 0x04, 0x0a, 0xe7, 0xbd, 0x8e, 0xc5, 0xdf,
	0x63, 0xf5, 0x54, 0xaa, 0xc9, 0x3c, 0x95, 0xe3, 0x1c, 0x15, 0x2e, 0x32, 0xe4, 0x05, 0x27, 0xfa,
	0x4a, 0x20, 0x6c, 0xf2, 0xa2, 0xa5, 0x58, 0x68, 0xa4, 0x31, 0x74, 0xcb, 0xd4, 0x9c, 0x99, 0xdb,
	0x56, 0x5c, 0xc9, 0xcc, 0xeb, 0x4d, 0x6d, 0x99, 0x3b, 0x58, 0xcd, 0x7d, 0xe7, 0xa2, 0xee, 0x9f,
	0xc1, 0xf5, 0xca, 0x65, 0x2f, 0xb0, 0xa4, 0x07, 0xac, 0xed, 0x60, 0x59, 0xe5, 0xf2, 0x60, 0x31,
	0x17, 0xdc, 0x73, 0xa3, 0x04, 0xee, 0x3c, 0xcf, 0xf5, 0xef, 0xa3, 0xe8, 0xd5, 0x73, 0x8d, 0xbe,
	0x13, 0xe8, 0x37, 0x4b, 0x5e, 0x61, 0x3c, 0xfb, 0xb0, 0x5e, 0x8d, 0xa8, 0x7b, 0xc1, 0x20, 0xb8,
	0x64, 0x3e, 0xbf, 0xc8, 0xd1, 0x04, 0x6e, 0xec, 0xa1, 0xd9, 0x17, 0xc7, 0xf8, 0x1f, 0x99, 0xfc,
	0x20, 0xb0, 0xe9, 0x55, 0xae, 0x30, 0x06, 0x0a, 0x6b, 0x32, 0x35, 0x6f, 0xed, 0x86, 0xac, 0x73,
	0xfb, 0xfb, 0xdc, 0xe6, 0xac, 0xad, 0xbe, 0x39, 0x3b, 0x9f, 0x02, 0xd8, 0xe0, 0x0e, 0xfb, 0x34,
	0x39, 0xa0, 0xef, 0x08, 0xd0, 0x3f, 0x2f, 0x05, 0x7d, 0xd4, 0x2e, 0xfe, 0xd7, 0x2b, 0x1d, 0x3e,
	0xbe, 0x3c, 0xd1, 0x25, 0xfb, 0x91, 0xc0, 0xad, 0xa6, 0x0d, 0xa4, 0xbb, 0xed, 0x92, 0x2d, 0x17,
	0x21, 0x7c, 0xb2, 0x0a, 0xd5, 0xf9, 0x99, 0xc3, 0x35, 0x77, 0xf8, 0x74, 0xfb, 0x9f, 0x43, 0xd5,
	0x36, 0x2d, 0x7c, 0x78, 0x41, 0x74, 0xd9, 0x67, 0xfc, 0x81, 0xc0, 0x20, 0x13, 0xc7, 0xad, 0xa4,
	0xf1, 0x4d, 0x7f, 0x66, 0x32, 0x4f, 0x8a, 0x97, 0x35, 0x21, 0xaf, 0x36, 0x2b, 0x94, 0x03, 0x7d,
	0xee, 0x04, 0x93, 0x29, 0xff, 0xd2, 0xe9, 0x4f, 0xf4, 0x88, 0xb9, 0xb1, 0x58, 0xc5, 0x63, 0x2f,
	0x87, 0xe3, 0x02, 0xf4, 0xcd, 0x96, 0x67, 0xae, 0x3c, 0xab, 0xca, 0x33, 0x57, 0x3e, 0xec, 0xda,
	0x77, 0x7b, 0xf4, 0x33, 0x00, 0x00, 0xff, 0xff, 0xe9, 0x48, 0x49, 0xb9, 0xa1, 0x06, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// RegistryAPIClient is the client API for RegistryAPI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type RegistryAPIClient interface {
	// Returns the storage provider that is reponsible for the given
	// resource reference.
	// MUST return CODE_NOT_FOUND if the reference does not exist.
	GetStorageProvider(ctx context.Context, in *GetStorageProviderRequest, opts ...grpc.CallOption) (*GetStorageProviderResponse, error)
	// Returns a list of the available storage providers known by this registry.
	ListStorageProviders(ctx context.Context, in *ListStorageProvidersRequest, opts ...grpc.CallOption) (*ListStorageProvidersResponse, error)
	// Returns the home path for the given authenticated user.
	// When a user has access to multiple storage providers, one of them is the home.
	GetHome(ctx context.Context, in *GetHomeRequest, opts ...grpc.CallOption) (*GetHomeResponse, error)
}

type registryAPIClient struct {
	cc *grpc.ClientConn
}

func NewRegistryAPIClient(cc *grpc.ClientConn) RegistryAPIClient {
	return &registryAPIClient{cc}
}

func (c *registryAPIClient) GetStorageProvider(ctx context.Context, in *GetStorageProviderRequest, opts ...grpc.CallOption) (*GetStorageProviderResponse, error) {
	out := new(GetStorageProviderResponse)
	err := c.cc.Invoke(ctx, "/cs3.storage.registry.v1beta1.RegistryAPI/GetStorageProvider", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *registryAPIClient) ListStorageProviders(ctx context.Context, in *ListStorageProvidersRequest, opts ...grpc.CallOption) (*ListStorageProvidersResponse, error) {
	out := new(ListStorageProvidersResponse)
	err := c.cc.Invoke(ctx, "/cs3.storage.registry.v1beta1.RegistryAPI/ListStorageProviders", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *registryAPIClient) GetHome(ctx context.Context, in *GetHomeRequest, opts ...grpc.CallOption) (*GetHomeResponse, error) {
	out := new(GetHomeResponse)
	err := c.cc.Invoke(ctx, "/cs3.storage.registry.v1beta1.RegistryAPI/GetHome", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RegistryAPIServer is the server API for RegistryAPI service.
type RegistryAPIServer interface {
	// Returns the storage provider that is reponsible for the given
	// resource reference.
	// MUST return CODE_NOT_FOUND if the reference does not exist.
	GetStorageProvider(context.Context, *GetStorageProviderRequest) (*GetStorageProviderResponse, error)
	// Returns a list of the available storage providers known by this registry.
	ListStorageProviders(context.Context, *ListStorageProvidersRequest) (*ListStorageProvidersResponse, error)
	// Returns the home path for the given authenticated user.
	// When a user has access to multiple storage providers, one of them is the home.
	GetHome(context.Context, *GetHomeRequest) (*GetHomeResponse, error)
}

// UnimplementedRegistryAPIServer can be embedded to have forward compatible implementations.
type UnimplementedRegistryAPIServer struct {
}

func (*UnimplementedRegistryAPIServer) GetStorageProvider(ctx context.Context, req *GetStorageProviderRequest) (*GetStorageProviderResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetStorageProvider not implemented")
}
func (*UnimplementedRegistryAPIServer) ListStorageProviders(ctx context.Context, req *ListStorageProvidersRequest) (*ListStorageProvidersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListStorageProviders not implemented")
}
func (*UnimplementedRegistryAPIServer) GetHome(ctx context.Context, req *GetHomeRequest) (*GetHomeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetHome not implemented")
}

func RegisterRegistryAPIServer(s *grpc.Server, srv RegistryAPIServer) {
	s.RegisterService(&_RegistryAPI_serviceDesc, srv)
}

func _RegistryAPI_GetStorageProvider_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStorageProviderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RegistryAPIServer).GetStorageProvider(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cs3.storage.registry.v1beta1.RegistryAPI/GetStorageProvider",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RegistryAPIServer).GetStorageProvider(ctx, req.(*GetStorageProviderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RegistryAPI_ListStorageProviders_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListStorageProvidersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RegistryAPIServer).ListStorageProviders(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cs3.storage.registry.v1beta1.RegistryAPI/ListStorageProviders",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RegistryAPIServer).ListStorageProviders(ctx, req.(*ListStorageProvidersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RegistryAPI_GetHome_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetHomeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RegistryAPIServer).GetHome(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cs3.storage.registry.v1beta1.RegistryAPI/GetHome",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RegistryAPIServer).GetHome(ctx, req.(*GetHomeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _RegistryAPI_serviceDesc = grpc.ServiceDesc{
	ServiceName: "cs3.storage.registry.v1beta1.RegistryAPI",
	HandlerType: (*RegistryAPIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetStorageProvider",
			Handler:    _RegistryAPI_GetStorageProvider_Handler,
		},
		{
			MethodName: "ListStorageProviders",
			Handler:    _RegistryAPI_ListStorageProviders_Handler,
		},
		{
			MethodName: "GetHome",
			Handler:    _RegistryAPI_GetHome_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "cs3/storage/registry/v1beta1/registry_api.proto",
}
